spring:
  application:
    name: client_server

server:
  port: 8888


application-server:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8090,localhost:8091
    ServerListRefreshInterval: 2000